services:
  api:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/api-meteo
    depends_on:
      database:
        condition: service_healthy
        restart: true

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./meteo.sql:/docker-entrypoint-initdb.d/meteo.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=meteo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=database
    depends_on:
      - database